apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/example/app-of-app/webapp-3
    repoURL: https://github.com/foxutech/kubernetes.git
    targetRevision: HEAD
