apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-1
  labels:
    app: webapp-1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp-1
  template:
    metadata:
      labels:
        app: webapp-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
