apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: sync-phases
spec:
  destination:
    namespace: phase-application
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd/sync/phases/
    repoURL: "https://github.com/foxutech/kubernetes.git"
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
