apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: track-commit
  namespace: argocd
spec:
  destination:
    namespace: track-commit
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/foxutech/kubernetes.git"
    targetRevision: 961d8b5
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
